# Use an official Node.js runtime as a parent image
FROM node:21.5.0-alpine

# Set the working directory in the container
WORKDIR /usr/app

# Copy package.json and package-lock.json to the working directory
COPY src/package*.json ./

# Install app dependencies
RUN npm install

# Bundle your app source
COPY src .

WORKDIR /usr/app/src

# At the end, set the user to use when running this image
USER node

# Expose the port your app will run on
EXPOSE 3000


# Define the command to run your app
CMD ["npm", "start"]